Produce graphs for irmin bench
tarides/irmin-scratch pull request #13
Opened 2022-05-13 12:05 UTC by icristescu

2022-05-13 12:15 UTC, maiste requested changes

2022-05-13 12:15 UTC, maiste commented on scripts/produce_graphs_irmin.py
> +# +--------------------------------------------+
```suggestion
# +---------------------------------------------+
# | Name: Irmin graph generator                 |
# | Author: Ioana Cristescu <ioana@tarides.com> |
# | Version: 20220513                           |
# +---------------------------------------------+
```

2022-05-13 16:25 UTC, icristescu commented on scripts/produce_graphs_irmin.py
> +# +--------------------------------------------+
thanks

2022-05-14 13:51 UTC, maiste approved these changes

2022-05-16 08:48 UTC, merged